DROP SEQUENCE NOSEQ;
DROP TABLE ABOARD;

CREATE SEQUENCE NOSEQ NOCACHE;
CREATE TABLE ABOARD(
    BNO NUMBER PRIMARY KEY,
    BNAME VARCHAR2(1000) NOT NULL,
    BPW VARCHAR2(50) NOT NULL,
    BTITLE VARCHAR2(2000) NOT NULL,
    BCONTENT VARCHAR2(4000) NOT NULL,
    BDATE DATE NOT NULL
);

INSERT INTO ABOARD VALUES(MYNOSEQ.NEXTVAL, '관리자','1','테스트','SPRING MVC 재밌다:)', SYSDATE);

SELECT * FROM ABOARD ORDER BY BNO DESC;

COMMIT;
----------------------------------------